db.BaiViet.insertMany([
  {
    _id: new ObjectId("123456789012123456789012"),
    text: "du lịch cùng sa sa 2",
    postType: "STATUS",
    visibility: "PUBLIC",
    media: {
      type: "images",
      data: [
        "https://xoaimedia.com/wp-content/uploads/2021/03/chup-anh-thu-cung-6.jpg",
      ],
    },
    taggedUsers: [],
    createAt: new Date(new Date().setSeconds(new Date().getHours() - 24 * 100)),
    numOfLike: 0,
    numOfComment: 0,
    modifiedAt: null,
    owner_id: 2,
    test: 1,
  },
  {
    _id: new ObjectId("123456789012123456789013"),
    text: "du lịch cùng sa sa 3",
    postType: "STATUS",
    visibility: "PUBLIC",
    media: {
      type: "images",
      data: [
        "https://xoaimedia.com/wp-content/uploads/2021/03/chup-anh-thu-cung-6.jpg",
      ],
    },
    taggedUsers: [],
    createAt: new Date(new Date().setSeconds(new Date().getHours() - 24 * 90)),
    numOfLike: 0,
    numOfComment: 0,
    modifiedAt: null,
    owner_id: 3,
    test: 1,
  },
  {
    _id: new ObjectId("123456789012123456789014"),
    text: "du lịch cùng sa sa 4",
    postType: "STATUS",
    visibility: "PUBLIC",
    media: {
      type: "images",
      data: [
        "https://xoaimedia.com/wp-content/uploads/2021/03/chup-anh-thu-cung-6.jpg",
      ],
    },
    taggedUsers: [],
    createAt: new Date(new Date().setSeconds(new Date().getHours() - 24 * 80)),
    numOfLike: 0,
    numOfComment: 0,
    modifiedAt: null,
    owner_id: 4,
    test: 1,
  },
  {
    _id: new ObjectId("123456789012123456789015"),
    text: "du lịch cùng sa sa 5",
    postType: "STATUS",
    visibility: "PUBLIC",
    media: {
      type: "images",
      data: [
        "https://xoaimedia.com/wp-content/uploads/2021/03/chup-anh-thu-cung-6.jpg",
      ],
    },
    taggedUsers: [],
    createAt: new Date(new Date().setSeconds(new Date().getHours() - 24 * 70)),
    numOfLike: 0,
    numOfComment: 0,
    modifiedAt: null,
    owner_id: 5,
    test: 1,
  },
  {
    _id: new ObjectId("123456789012123456789016"),
    text: "du lịch cùng sa sa 6",
    postType: "STATUS",
    visibility: "PUBLIC",
    media: {
      type: "images",
      data: [
        "https://xoaimedia.com/wp-content/uploads/2021/03/chup-anh-thu-cung-6.jpg",
      ],
    },
    taggedUsers: [],
    createAt: new Date(new Date().setSeconds(new Date().getHours() - 24 * 60)),
    numOfLike: 0,
    numOfComment: 0,
    modifiedAt: null,
    owner_id: 6,
    test: 1,
  },
  {
    _id: new ObjectId("123456789012123456789017"),
    text: "du lịch cùng sa sa 7",
    postType: "STATUS",
    visibility: "PUBLIC",
    media: {
      type: "images",
      data: [
        "https://xoaimedia.com/wp-content/uploads/2021/03/chup-anh-thu-cung-6.jpg",
      ],
    },
    taggedUsers: [],
    createAt: new Date(new Date().setSeconds(new Date().getHours() - 24 * 50)),
    numOfLike: 0,
    numOfComment: 0,
    modifiedAt: null,
    owner_id: 7,
    test: 1,
  },
  {
    _id: new ObjectId("123456789012123456789018"),
    text: "du lịch cùng sa sa 8",
    postType: "STATUS",
    visibility: "PUBLIC",
    media: {
      type: "images",
      data: [
        "https://xoaimedia.com/wp-content/uploads/2021/03/chup-anh-thu-cung-6.jpg",
      ],
    },
    taggedUsers: [],
    createAt: new Date(new Date().setSeconds(new Date().getHours() - 24 * 40)),
    numOfLike: 0,
    numOfComment: 0,
    modifiedAt: null,
    owner_id: 8,
    test: 1,
  },
  {
    _id: new ObjectId("123456789012123456789019"),
    text: "du lịch cùng sa sa 9",
    postType: "STATUS",
    visibility: "PUBLIC",
    media: {
      type: "images",
      data: [
        "https://xoaimedia.com/wp-content/uploads/2021/03/chup-anh-thu-cung-6.jpg",
      ],
    },
    taggedUsers: [],
    createAt: new Date(new Date().setSeconds(new Date().getHours() - 24 * 30)),
    numOfLike: 0,
    numOfComment: 0,
    modifiedAt: null,
    owner_id: 9,
    test: 1,
  },
  {
    _id: new ObjectId("123456789012123456789020"),
    text: "du lịch cùng sa sa 10",
    postType: "STATUS",
    visibility: "PUBLIC",
    media: {
      type: "images",
      data: [
        "https://xoaimedia.com/wp-content/uploads/2021/03/chup-anh-thu-cung-6.jpg",
      ],
    },
    taggedUsers: [],
    createAt: new Date(new Date().setSeconds(new Date().getHours() - 24 * 20)), // hihi
    numOfLike: 0,
    numOfComment: 0,
    modifiedAt: null,
    owner_id: 10,
    test: 1,
  },

  {
    _id: new ObjectId("123456789012123456789021"),
    text: "du lịch cùng sa sa 11",
    postType: "STATUS",
    visibility: "PUBLIC",
    media: {
      type: "images",
      data: [
        "https://xoaimedia.com/wp-content/uploads/2021/03/chup-anh-thu-cung-6.jpg",
      ],
    },
    taggedUsers: [],
    createAt: new Date(new Date().setSeconds(new Date().getHours() - 24 * 11)),
    numOfLike: 0,
    numOfComment: 0,
    modifiedAt: null,
    owner_id: 11,
    test: 1,
  },
  {
    _id: new ObjectId("123456789012123456789022"),
    text: "du lịch cùng sa sa 12",
    postType: "STATUS",
    visibility: "PUBLIC",
    media: {
      type: "images",
      data: [
        "https://xoaimedia.com/wp-content/uploads/2021/03/chup-anh-thu-cung-6.jpg",
      ],
    },
    taggedUsers: [],
    createAt: new Date(new Date().setSeconds(new Date().getHours() - 24 * 12)),
    numOfLike: 0,
    numOfComment: 0,
    modifiedAt: null,
    owner_id: 12,
    test: 1,
  },
  {
    _id: new ObjectId("123456789012123456789023"),
    text: "du lịch cùng sa sa 13",
    postType: "STATUS",
    visibility: "PUBLIC",
    media: {
      type: "images",
      data: [
        "https://xoaimedia.com/wp-content/uploads/2021/03/chup-anh-thu-cung-6.jpg",
      ],
    },
    taggedUsers: [],
    createAt: new Date(new Date().setSeconds(new Date().getHours() - 24 * 13)),
    numOfLike: 0,
    numOfComment: 0,
    modifiedAt: null,
    owner_id: 13,
    test: 1,
  },
  {
    _id: new ObjectId("123456789012123456789024"),
    text: "du lịch cùng sa sa 14",
    postType: "STATUS",
    visibility: "PUBLIC",
    media: {
      type: "images",
      data: [
        "https://xoaimedia.com/wp-content/uploads/2021/03/chup-anh-thu-cung-6.jpg",
      ],
    },
    taggedUsers: [],
    createAt: new Date(new Date().setSeconds(new Date().getHours() - 24 * 14)),
    numOfLike: 0,
    numOfComment: 0,
    modifiedAt: null,
    owner_id: 14,
    test: 1,
  },
  {
    _id: new ObjectId("123456789012123456789025"),
    text: "du lịch cùng sa sa 15",
    postType: "STATUS",
    visibility: "PUBLIC",
    media: {
      type: "images",
      data: [
        "https://xoaimedia.com/wp-content/uploads/2021/03/chup-anh-thu-cung-6.jpg",
      ],
    },
    taggedUsers: [],
    createAt: new Date(new Date().setSeconds(new Date().getHours() - 24 * 15)),
    numOfLike: 0,
    numOfComment: 0,
    modifiedAt: null,
    owner_id: 15,
    test: 1,
  },
  {
    _id: new ObjectId("123456789012123456789026"),
    text: "du lịch cùng sa sa 16",
    postType: "STATUS",
    visibility: "PUBLIC",
    media: {
      type: "images",
      data: [
        "https://xoaimedia.com/wp-content/uploads/2021/03/chup-anh-thu-cung-6.jpg",
      ],
    },
    taggedUsers: [],
    createAt: new Date(new Date().setSeconds(new Date().getHours() - 24 * 16)),
    numOfLike: 0,
    numOfComment: 0,
    modifiedAt: null,
    owner_id: 16,
    test: 1,
  },
  {
    _id: new ObjectId("123456789012123456789027"),
    text: "du lịch cùng sa sa 17",
    postType: "STATUS",
    visibility: "PUBLIC",
    media: {
      type: "images",
      data: [
        "https://xoaimedia.com/wp-content/uploads/2021/03/chup-anh-thu-cung-6.jpg",
      ],
    },
    taggedUsers: [],
    createAt: new Date(new Date().setSeconds(new Date().getHours() - 24 * 17)),
    numOfLike: 0,
    numOfComment: 0,
    modifiedAt: null,
    owner_id: 17,
    test: 1,
  },
  {
    _id: new ObjectId("123456789012123456789028"),
    text: "du lịch cùng sa sa 18",
    postType: "STATUS",
    visibility: "PUBLIC",
    media: {
      type: "images",
      data: [
        "https://xoaimedia.com/wp-content/uploads/2021/03/chup-anh-thu-cung-6.jpg",
      ],
    },
    taggedUsers: [],
    createAt: new Date(new Date().setSeconds(new Date().getHours() - 24 * 18)),
    numOfLike: 0,
    numOfComment: 0,
    modifiedAt: null,
    owner_id: 18,
    test: 1,
  },
  {
    _id: new ObjectId("123456789012123456789029"),
    text: "du lịch cùng sa sa 19",
    postType: "STATUS",
    visibility: "PUBLIC",
    media: {
      type: "images",
      data: [
        "https://xoaimedia.com/wp-content/uploads/2021/03/chup-anh-thu-cung-6.jpg",
      ],
    },
    taggedUsers: [],
    createAt: new Date(new Date().setSeconds(new Date().getHours() - 24 * 19)),
    numOfLike: 0,
    numOfComment: 0,
    modifiedAt: null,
    owner_id: 19,
    test: 1,
  },
  {
    _id: new ObjectId("123456789012123456789030"),
    text: "du lịch cùng sa sa 20",
    postType: "STATUS",
    visibility: "PUBLIC",
    media: {
      type: "images",
      data: [
        "https://xoaimedia.com/wp-content/uploads/2021/03/chup-anh-thu-cung-6.jpg",
      ],
    },
    taggedUsers: [],
    createAt: new Date(new Date().setSeconds(new Date().getHours() - 24 * 20)),
    numOfLike: 0,
    numOfComment: 0,
    modifiedAt: null,
    owner_id: 20,
    test: 1,
  },
]);