[
  {
    _id: "64fd4517b00c4d6c5dc9a9ed",
    text: "nam 1",
    postType: "STATUS",
    visibility: "PUBLIC",
    media: {
      type: "images",
      data: ["google.com", "facebook.com"],
    },
    taggedUsers:[],
	createAt: new Date(),
    numOfLike: 0,
    numOfComment: 0,
    owner_id: 1,
  },
  {
    _id: "64fd4517b00c4d6c5dc9a9ee",
    text: "nam 2",
    postType: "STATUS",
    visibility: "PUBLIC",
    media: undefined,
    taggedUsers:[],
	createAt: new Date(),
    numOfLike: 0,
    numOfComment: 0,
    owner_id: 1,
  },

  {
    _id: "64fd4517b00c4d6c5dc9a9ef",
    text: "Dung 3",
    postType: "STATUS",
    visibility: "PUBLIC",
    media: {
      type: "video",
      data: ["titok.com"],
    },
    taggedUsers:[],
	createAt: new Date(),
    numOfLike: 0,
    numOfComment: 0,
    owner_id: 2,
  },
];

[
  {
    _id: "64fd4549b00c4d6c5dc9a9f0",
    text: "nam 3",
    postType: "STATUS",
    visibility: "PUBLIC",
    media: {
      type: "video",
      data: ["titok.com"],
    },
    taggedUsers:[],
	createAt: new Date(),
    numOfLike: 0,
    numOfComment: 0,
    owner_id: 1,
  },

  {
    _id: "64fd4549b00c4d6c5dc9a9f1",
    text: "Dung 1",
    postType: "STATUS",
    visibility: "PUBLIC",
    media: {
      type: "images",
      data: ["google.com", "facebook.com"],
    },
    taggedUsers:[],
	createAt: new Date(),
    numOfLike: 0,
    numOfComment: 0,
    owner_id: 2,
  },
  {
    _id: "64fd4549b00c4d6c5dc9a9f2",
    text: "Dung 2",
    postType: "STATUS",
    visibility: "PUBLIC",
    media: undefined,
    taggedUsers:[],
	createAt: new Date(),
    numOfLike: 0,
    numOfComment: 0,
    owner_id: 2,
  },
];
